hw_web_10/hw_web_10/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('quotes.urls')),
    path('users/', include('users.urls')),
]

hw_web_10/quotes/urls.py
from django.urls import path
from . import views

app_name = 'quotes'

urlpatterns = [
    path('quotes/', views.main, name='quotes_list'),
    path('author/<str:author_fullname>/', views.author_detail, name='author_detail'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
]

hw_web_10/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

hw_web_10/quotes/models.py
from mongoengine import Document, StringField, ListField, ReferenceField

class Authors(Document):
    fullname = StringField(required=True)
    born_date = StringField(required=True)
    born_location = StringField(required=True)
    description = StringField(required=True)


class Quotes(Document):
    tags = ListField(StringField())
    author = ReferenceField(Authors)
    quote = StringField(required=True)

hw_web_10/users/models.py
from django.db import models

# Create your models here.

hw_web_10/quotes/forms.py
from django import forms


class AuthorsForm(forms.Form):
    fullname = forms.CharField(max_length=100)
    born_date = forms.CharField(max_length=100)
    born_location = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea)

class QuotesForm(forms.Form):
    quote = forms.CharField(widget=forms.Textarea)
    author = forms.CharField(max_length=100)
    tags = forms.CharField(max_length=100)

hw_web_10/quotes/views.py
from django.shortcuts import render,redirect
from django.http import Http404
from .models import Quotes,Authors
from django.contrib.auth.decorators import login_required
from .forms import AuthorsForm, QuotesForm

from .forms import AuthorsForm, QuotesForm
from .models import Authors, Quotes


@login_required
def add_author(request):
    if request.method == 'POST':
        form = AuthorsForm(request.POST)
        if form.is_valid():
            author_data = form.cleaned_data
            author = Authors(
                fullname=author_data['fullname'],
                born_date=author_data['born_date'],
                born_location=author_data['born_location'],
                description=author_data['description']
            )
            author.save()
            return redirect('quotes:quotes_list')  
    else:
        form = AuthorsForm()
    return render(request, 'quotes/add_author.html', {'form': form})

@login_required
def add_quote(request):
    if request.method == 'POST':
        form = QuotesForm(request.POST)
        if form.is_valid():
            quote_data = form.cleaned_data
            author_name = quote_data.pop('author')  
            author = Authors.objects.get(fullname=author_name)  
            tags = quote_data.pop('tags').split(',')  
            quote = Quotes(
                author=author,
                tags=tags,
                quote=quote_data['quote']
            )
            quote.save()
            return redirect('quotes:quotes_list')  
    else:
        form = QuotesForm()
    return render(request, 'quotes/add_quote.html', {'form': form})


def main(request):
    quotes = Quotes.objects.all()
    return render(request, 'quotes/quotes_list.html', {'quotes': quotes})

def author_detail(request, author_fullname):
    try:
        author = Authors.objects.get(fullname=author_fullname)
    except Authors.DoesNotExist:
        raise Http404("Автор не знайдений")
    return render(request, 'quotes/author_detail.html', {'author': author})

hw_web_10/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login, logout as auth_logout

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = UserCreationForm()
    return render(request, 'users/signup.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('quotes:quotes_list')  
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})

def logout(request):
    auth_logout(request)
    return redirect('quotes:quotes_list')  

hw_web_10/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block title %}Add author{% endblock %}

{% block content %}
    <h2>Add Author</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

hw_web_10/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block title %}Add quote{% endblock %}

{% block content %}
    <h2>Add Quote</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

hw_web_10/quotes/templates/quotes/author_detail.html
{% extends './base.html' %}

{% block title %}Author{% endblock %}
{% block header %}Author{% endblock %}

{% block content %}
<div class="card">
    <div class="card-body">
        <h2 class="card-title">{{ author.fullname }}</h2>
        <p class="card-text">Born: {{ author.born_date }}</p>
        <p class="card-text">Place: {{ author.born_location }}</p>
        <p class="card-text">{{ author.description }}</p>
    </div>
</div>
{% endblock %}

hw_web_10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Quotes To Scrape{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <div class="d-flex justify-content-end mb-4">
            {% if user.is_authenticated %}
                <p class="mr-3">Welcome, {{ user.username }}!</p>
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                <a href="{% url 'quotes:add_author' %}" class="btn btn-success ml-2">Add Author</a>
                <a href="{% url 'quotes:add_quote' %}" class="btn btn-success ml-2">Add Quote</a>
            {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-primary mr-3">Login</a>
                <a href="{% url 'users:register' %}" class="btn btn-secondary">Register</a>
            {% endif %}
        </div>
        <h1 class="text-center mb-4 ml-4">{% block header %}Quotes To Scrape{% endblock %}</h1>
        {% block content %}{% endblock %}
    </div>
</body>
</html>

hw_web_10/quotes/templates/quotes/quotes_list.html
{% extends './base.html' %}

{% block content %}
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>Quote</th>
                <th>Author</th>
                <th>Tags</th>
            </tr>
        </thead>
        <tbody>
            {% for quote in quotes %}
            <tr>
                <td>{{ quote.quote }}</td>
                <td><a href="{% url 'quotes:author_detail' author_fullname=quote.author.fullname %}">{{ quote.author.fullname }}</a></td>
                <td>
                    {% for tag in quote.tags %}
                    <span class="badge badge-info">{{ tag }}</span>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

hw_web_10/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
{% endblock %}

hw_web_10/users/templates/users/signup.html
{% extends 'quotes/base.html' %}

{% block title %}
Register
{% endblock %}

{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Register</button>
</form>
{% endblock %}